language: android
os:
    - linux

jdk:
    - oraclejdk8

notifications:
  email:
    recipients:
        - atmosphere@musala.com

android:
    components:
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-25
    - extra

cache:
    directories:
        - $HOME/.gradle

before_script:
    - chmod +x gradlew

script:
    - ./gradlew build
